###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
global:
  image:
    secretName: ""
  id:
    productID: "IBMCloudAutomationManager_5737E67_3100_CE_000"
  iam:
    deployApiKey: ""
  offline: false
  audit: false

#arch: ppc64le
arch: amd64

service:
  namespace: services

managementConsole:
  port: 30000

secureValues: 
  secretName: ""

database:
  bundled: true

redis:
  bundled: true
  host: redis
  port: 6379

image:
  repository: "store/ibmcorp/"
  tag: 3.1.0.0
  pullPolicy: IfNotPresent
  dockerconfig: ""

proxy:
  useProxy: false

ipamMongoPV:
  name: "ipam-mongo-pv"
  persistence:
    enabled: true
    useDynamicProvisioning: false

    ## Specify the name of the Existing Claim to be used by your application
    ## empty string means don't use an existClaim
    existingClaimName: ""

    ## Specify the name of the StorageClass
    ## empty string means don't use a StorageClass
    storageClassName: ""

    accessMode: ReadWriteMany

    size: 15Gi

ipamLogsPV:
  name: "ipam-logs-pv"
  persistence:
    enabled: true
    useDynamicProvisioning: false

    ## Specify the name of the Existing Claim to be used by your application
    ## empty string means don't use an existClaim
    existingClaimName: ""

    ## Specify the name of the StorageClass
    ## empty string means don't use a StorageClass
    storageClassName: ""

    accessMode: ReadWriteMany

    size: 10Gi

ipamTerraformPV:
  name: "ipam-terraform-pv"
  persistence:
    enabled: true
    useDynamicProvisioning: false

    ## Specify the name of the Existing Claim to be used by your application
    ## empty string means don't use an existClaim
    existingClaimName: ""

    ## Specify the name of the StorageClass
    ## empty string means don't use a StorageClass
    storageClassName: ""

    accessMode: ReadWriteMany

    size: 15Gi

ipamBPDAppDataPV:
  name: "ipam-bpd-appdata-pv"
  persistence:
    enabled: true
    useDynamicProvisioning: false
    existingClaimName: ""
    storageClassName: ""
    accessMode: ReadWriteMany
    size: 15Gi

ipamBroker:
  replicaCount: 1

ipamProxy:
  replicaCount: 1

ipamAPI:
  replicaCount: 1
  ipamSecret:
    secretName: ipam-api-secret
  certificate:
    certName: cert
    certPath: /usr/src/app/certs

ipamUI:
  replicaCount: 1
  ipamUISecret:
    secretName: ipam-ui-secret
    sessionKey: "opsConsole.sid"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 8Gi

ipamBPDUI:
  bundled: true

ipamBPDCDS:
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
  options:
    debug:
      enabled: false
    customSettingsFile: ""

ipamBPDMDS:
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

ipamBPDDatabase:
  bundled: true
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

ipamBPDExternalDatabase:
  type: ""
  name: ""
  url: ""
  port: ""
  secret: ""
  extlibPV:
    existingClaimName: ""

ipamBPDResources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

auditService:
  image:
    repository: "mycluster.icp:8500/ibmcom/"
    tag: 3.1.0
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  extraArgs: {}

  config:
    journalPath: '/run/systemd/journal'

ipamLoggingPolicies:
  logLevel: info